### ISSUE TITLE
Print Warnings for Issues with Dependent Component Status

### ISSUE THREAD

**Issue by spmacdonald** [lanl-ansi/PowerModels.jl#547] opened 2019-06-20 20:52 UTC
When I try to run the following code:

```
using PowerModels
using JuMP
using Ipopt

data = PowerModels.parse_file("network-model.RAW")
ipopt_solver = with_optimizer(Ipopt.Optimizer, print_level=0)
result = run_dc_opf(data, ipopt_solver, setting = Dict("output" => Dict("branch_flows" => true)))
```

I get the following error:

```
ERROR: LoadError: KeyError: key 3757 not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] lookup_index at /home/vagrant/.julia/packages/JuMP/ibcEh/src/Containers/DenseAxisArray.jl:136 [inlined]
 [3] _to_index_tuple at /home/vagrant/.julia/packages/JuMP/ibcEh/src/Containers/DenseAxisArray.jl:145 [inlined]
 [4] to_index at /home/vagrant/.julia/packages/JuMP/ibcEh/src/Containers/DenseAxisArray.jl:163 [inlined]
 [5] getindex(::JuMP.Containers.DenseAxisArray{VariableRef,1,Tuple{Base.KeySet{Int64,Dict{Int64,Any}}},Tuple{Dict{Int64,Int64}}}, ::Int64) at /home/vagrant/.julia/packages/JuMP/ibcEh/src/Containers/DenseAxisArray.jl:177
 [6] #add_setpoint!#429(::String, ::getfield(PowerModels, Symbol("##434#441")), ::getfield(PowerModels, Symbol("##435#442")), ::getfield(PowerModels, Symbol("##436#443")), ::Dict{String,Any}, ::Bool, ::String, ::Int64, ::typeof(add_setpoint!), ::Dict{String,Any}, ::GenericPowerModel{DCPlosslessForm}, ::String, ::String, ::Symbol) at /home/vagrant/.julia/packages/PowerModels/mI6yi/src/core/solution.jl:202
 [7] (::getfield(PowerModels, Symbol("#kw##add_setpoint!")))(::NamedTuple{(:status_name,),Tuple{String}}, ::typeof(add_setpoint!), ::Dict{String,Any}, ::GenericPowerModel{DCPlosslessForm}, ::String, ::String, ::Symbol) at ./none:0
 [8] add_setpoint_generator_power! at /home/vagrant/.julia/packages/PowerModels/mI6yi/src/core/solution.jl:96 [inlined]
 [9] solution_opf!(::GenericPowerModel{DCPlosslessForm}, ::Dict{String,Any}) at /home/vagrant/.julia/packages/PowerModels/mI6yi/src/core/solution.jl:63
 [10] #build_solution#404(::typeof(solution_opf!), ::Function, ::GenericPowerModel{DCPlosslessForm}, ::Float64) at /home/vagrant/.julia/packages/PowerModels/mI6yi/src/core/solution.jl:30
 [11] (::getfield(PowerModels, Symbol("#kw##build_solution")))(::NamedTuple{(:solution_builder,),Tuple{typeof(solution_opf!)}}, ::typeof(build_solution), ::GenericPowerModel{DCPlosslessForm}, ::Float64) at ./none:0
 [12] #optimize_model!#179(::Function, ::Function, ::GenericPowerModel{DCPlosslessForm}, ::OptimizerFactory) at /home/vagrant/.julia/packages/PowerModels/mI6yi/src/core/base.jl:236
 [13] #run_model#176 at ./none:0 [inlined]
 [14] #run_model at ./none:0 [inlined]
 [15] #run_opf#638 at /home/vagrant/.julia/packages/PowerModels/mI6yi/src/prob/opf.jl:13 [inlined]
 [16] #run_opf at ./none:0 [inlined]
 [17] #run_dc_opf#637 at /home/vagrant/.julia/packages/PowerModels/mI6yi/src/prob/opf.jl:8 [inlined]
 [18] (::getfield(PowerModels, Symbol("#kw##run_dc_opf")))(::NamedTuple{(:setting,),Tuple{Dict{String,Dict{String,Bool}}}}, ::typeof(run_dc_opf), ::Dict{String,Any}, ::OptimizerFactory) at ./none:0
 [19] top-level scope at none:0
 [20] include at ./boot.jl:326 [inlined]
 [21] include_relative(::Module, ::String) at ./loading.jl:1038
 [22] include(::Module, ::String) at ./sysimg.jl:29
 [23] exec_options(::Base.JLOptions) at ./client.jl:267
 [24] _start() at ./client.jl:436
```

```
(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [b6b21f68] Ipopt v0.5.4
  [682c06a0] JSON v0.20.0
  [4076af6c] JuMP v0.19.2
  [c36e90e8] PowerModels v0.12.0 #master (https://github.com/lanl-ansi/PowerModels.jl)
```

Any thoughts on how I can debug this?  

Thank you

**Comment by ccoffrin** [comment] 2019-06-20 21:14
I tested "case5.m" on PowerModels v0.12.1 and I could not reproduce.  Can you check if this was fixed in v0.12.1?  If not, can you think of any special features that your test network would have that are not in "case5.m"?

**Comment by spmacdonald** [comment] 2019-06-20 22:57
I will check in more detail tomorrow at the office but one thing that comes to mind is fixed shunts.

**Comment by spmacdonald** [comment] 2019-06-21 13:25
Looks like the problem still exists for v0.12.1:

```
(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [b6b21f68] Ipopt v0.5.4
  [682c06a0] JSON v0.20.0
  [4076af6c] JuMP v0.19.2
  [c36e90e8] PowerModels v0.12.1 #master (https://github.com/lanl-ansi/PowerModels.jl)
```

I tried with a few other of my cases and the same problem exists.

These cases are produced by downloading the RAW files in v30 format and converting them to v33 using PowerWorld.  PowerModels is able to read these files with a few warnings.

I also tried to reproduce the problem using different public cases from https://electricgrids.engr.tamu.edu/ but was unable to trigger the error.

Is it possible that `build_ref` is removing disconnected components and then cannot find them later?

**Comment by ccoffrin** [comment] 2019-06-21 14:20
I think you are correct, the disconnect is most likely an inconsistency between the status filtering used in `build_ref` and in `build_solution`.  Can you check that all of the generator "gen_status" values are 0 or 1?

Also if you are able to send me an example directly I would be happy to debug it.

**Comment by spmacdonald** [comment] 2019-06-21 14:56
I'll try to create a case that triggers the error.  I can't send you these cases unfortunately because they are CEII.

Is this where build_ref is defined?

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/base.jl#L324


To help me understand, the "3757" key above is supposed to be in ref[:gen] right?

This is not a bus number but an internal index?

The keys of  `data["gen"]` are bus indicies as defined in the case, is that correct?

**Comment by ccoffrin** [comment] 2019-06-21 16:18
Every component in PowerModels has a unique integer id.  The keys of data["gen"] are this unique id, in the case of generators it should be 1 to n based on the rows in the generator list in the raw file.

The field "gen_bus" contains the bus id that the generator is connected to.

**Comment by spmacdonald** [comment] 2019-06-21 17:01
Ok so if "3757" is the index of a generator:

```
julia> data["gen"]["3757"]
Dict{String,Any} with 17 entries:
  "pg"         => 0.0
  "model"      => 2
  "shutdown"   => 0.0
  "startup"    => 0.0
  "qg"         => 0.0
  "gen_bus"    => 18272
  "pmax"       => 0.0
  "vg"         => 1.0
  "mbase"      => 0.0
  "source_id"  => Any["generator", 18272, "1 "]
  "index"      => 3757
  "cost"       => [100.0, 0.0]
  "gen_status" => 1
  "qmax"       => 99.99
  "qmin"       => -99.99
  "pmin"       => 0.0
  "ncost"      => 2
```

It should not be filtered out right?

In this case there are 3842 generator records, I verified this in PowerWorld and by manually counting the rows in the RAW file.

After loading the case with `parse_file` I see 3842 rows:

```
julia> data["gen"]
Dict{String,Any} with 3842 entries:
```

Then after `build_ref` I get 3512 entries.  Do you expect key "3757" to be in ref[:gen]?  If so this is the problem,

```
julia> ref[:gen][3757]
ERROR: KeyError: key 3757 not found
```

I verified all `gen_status` values are 0 or 1.

**Comment by ccoffrin** [comment] 2019-06-21 17:06
Based on the data you show, yes the integer key `3757` should appear in `ref[:gen]`.

**Comment by spmacdonald** [comment] 2019-06-21 17:36
Is there another reason it could be filtered out?

In the case the pmin/pmax for that generator are both 0 which seems odd to me.

**Comment by spmacdonald** [comment] 2019-06-21 18:08
I think I see the problem.

`build_ref` will filter out generators if `gen["gen_bus"] in keys(ref[:bus])` is false.  This appears to be the case:

```
julia> data["gen"]["3757"]
Dict{String,Any} with 17 entries:
  "pg"         => 0.0
  "model"      => 2
  "shutdown"   => 0.0
  "startup"    => 0.0
  "qg"         => 0.0
  "gen_bus"    => 18272
  "pmax"       => 0.0
  "vg"         => 1.0
  "mbase"      => 0.0
  "source_id"  => Any["generator", 18272, "1 "]
  "index"      => 3757
  "cost"       => [100.0, 0.0]
  "gen_status" => 1
  "qmax"       => 99.99
  "qmin"       => -99.99
  "pmin"       => 0.0
  "ncost"      => 2
```

But

```
julia> data["bus"]["18272"]
Dict{String,Any} with 12 entries:
  "zone"      => 20
  "bus_i"     => 18272
  "bus_type"  => 4
  "name"      => "LANDSTWN    "
  "vmax"      => 1.1
  "source_id" => ["bus", "18272"]
  "area"      => 1
  "vmin"      => 0.9
  "index"     => 18272
  "va"        => 0.0
  "vm"        => 1.0
  "base_kv"   => 230.0
```

bus_type = 4 means disconnected or isolated bus, and is therefore removed from `ref[:bus]`

The question now is what is the correct way to proceed?  It feels like a problem with the case?  I think I should set the gen_status to 0 for any gen_buses that have a bus_type == 4, what do you think?

Thanks a lot for your help tracking this down.

**Comment by ccoffrin** [comment] 2019-06-21 18:38
Ok, that suggests this is a data error, a generator should not be active when its bus is inactive.  I will think about how to generate a better error message in this case.

Can you test if this fixes your problem
```
data = PowerModels.parse_file("network-model.RAW")
PowerModels.propagate_topology_status!(data)
...
```

**Comment by spmacdonald** [comment] 2019-06-21 19:56
Yes that fixes the error I was seeing.

Do you recommend I use this method in general?

**Comment by ccoffrin** [comment] 2019-06-21 20:47
Yes.  It will correct any status values that don't make sense.  I will also add an automatic data quality checker that will print warnings when this specific issue.

**Comment by spmacdonald** [comment] 2019-06-21 21:01
Thanks again for your help

**Closed** 2019-06-22 14:58 UTC
