### ISSUE TITLE
component_table does not display if followed by statement

### ISSUE THREAD

**Issue by sidwan02** [lanl-ansi/PowerModels.jl#828] opened 2022-06-07 19:52 UTC
Borrowing from the first few lines of [dc-opf.jl in PowerModelsAnnex](https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/master/src/model/dc-opf.jl) and the [Network Data example in the PowerModels.jl documentation](https://lanl-ansi.github.io/PowerModels.jl/stable/network-data/):

Put the following snippet into some file `git-issue.jl`.
```
using PowerModels
using JuMP

powermodels_path = joinpath(dirname(pathof(PowerModels)), "..")

file_name = "$(powermodels_path)/test/data/matpower/case5.m"

data = PowerModels.parse_file(file_name)
PowerModels.component_table(data, "bus", ["vmin", "vmax"])
```

Running `include("git-issue.jl")` from within the Julia REPL prints a table as expected.

However, adding the following causes the table output in the REPL to disappear:

```
println("hi")
```
or even
```
a = 1
```

This issue _cannot_ be reproduced for a similar-purpose function like `PowerModels.print_summary`

**Comment by ccoffrin** [comment] 2022-08-14 00:08
I followed these instructions but was not able to reproduce the issue when working from the Julia REPL at the terminal.  I suspect this is an issue with your local setup, so I am going to close this issue.

**Closed by ccoffrin** 2022-08-14 00:08 UTC
