### ISSUE TITLE
test PowerModel failed

### ISSUE THREAD

**Issue by melek2** [lanl-ansi/PowerModels.jl#930] opened 2024-10-14 21:43 UTC
when testing the package by running 'test PowerModels', I get the error bellow. The program crashes at soc distflow pf_bf at 3-bus case. Below is the full code.
I am running this on MacBook Pro with an M2 chip and OS of Sequoia 15.0.1. I tried uninstalling then installing the PowerModels package but no success. Any help would be greatly appreciated!

(@v1.11) pkg> test PowerModels
     Testing PowerModels
      Status `/private/var/folders/ym/z79dll090wxf8wncdssnz92r0000gn/T/jl_23uUc3/Project.toml`
  [87dc4568] HiGHS v1.9.3
  [2030c09a] InfrastructureModels v0.7.8
  [b6b21f68] Ipopt v1.6.6
  [682c06a0] JSON v0.21.4
  [4076af6c] JuMP v1.23.2
  [2ddba703] Juniper v0.9.2
  [f28f55f0] Memento v1.4.1
  [2774e3e8] NLsolve v4.5.1
  [c36e90e8] PowerModels v0.21.2
  [c946c3f1] SCS v2.0.1
  [37e2e46d] LinearAlgebra v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [8dfed614] Test v1.11.0
      Status `/private/var/folders/ym/z79dll090wxf8wncdssnz92r0000gn/T/jl_23uUc3/Manifest.toml`
  [79e6a3ab] Adapt v4.0.4
  [4fba245c] ArrayInterface v7.16.0
  [6e4b80f9] BenchmarkTools v1.5.0
  [523fee87] CodecBzip2 v0.8.4
  [944b1d66] CodecZlib v0.7.6
  [bbf7d656] CommonSubexpressions v0.3.1
  [34da2185] Compat v4.16.0
  [187b0558] ConstructionBase v1.5.8
  [864edb3b] DataStructures v0.18.20
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [b4f34e82] Distances v0.10.11
  [ffbed154] DocStringExtensions v0.9.3
  [6a86dc24] FiniteDiff v2.26.0
  [f6369f11] ForwardDiff v0.10.36
  [87dc4568] HiGHS v1.9.3
  [2030c09a] InfrastructureModels v0.7.8
  [b6b21f68] Ipopt v1.6.6
  [92d709cd] IrrationalConstants v0.2.2
  [692b3bcd] JLLWrappers v1.6.1
  [682c06a0] JSON v0.21.4
  [4076af6c] JuMP v1.23.2
  [2ddba703] Juniper v0.9.2
  [d3d80556] LineSearches v7.3.0
  [2ab3a3ac] LogExpFunctions v0.3.28
  [1914dd2f] MacroTools v0.5.13
  [b8f27783] MathOptInterface v1.31.2
  [f28f55f0] Memento v1.4.1
  [d8a4904e] MutableArithmetics v1.5.1
  [d41bc354] NLSolversBase v7.8.3
  [2774e3e8] NLsolve v4.5.1
  [77ba4419] NaNMath v1.0.2
  [bac558e1] OrderedCollections v1.6.3
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.8.1
  [c36e90e8] PowerModels v0.21.2
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [c946c3f1] SCS v2.0.1
  [efcf1570] Setfield v1.1.1
  [276daf66] SpecialFunctions v2.4.0
  [1e83bf80] StaticArraysCore v1.4.3
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.7.0
  [3bb67fe8] TranscodingStreams v0.11.3
  [3a884ed6] UnPack v1.0.2
  [ae81ac8f] ASL_jll v0.1.3+0
  [6e34b625] Bzip2_jll v1.0.8+1
  [8fd58aa0] HiGHS_jll v1.7.2+0
  [e33a78d0] Hwloc_jll v2.11.2+0
  [9cc047cb] Ipopt_jll v300.1400.1600+0
  [1d63c593] LLVMOpenMP_jll v18.1.7+0
  [d00139f3] METIS_jll v5.1.2+0
⌅ [d7ed1dd3] MUMPS_seq_jll v500.700.300+0
  [656ef2d0] OpenBLAS32_jll v0.3.28+3
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
⌅ [f4f2fc5b] SCS_jll v3.2.6+0
  [319450e9] SPRAL_jll v2024.5.8+0
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [9abbd945] Profile v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [05823500] OpenLibm_jll v0.8.1+2
  [bea87d4a] SuiteSparse_jll v7.7.0+0
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading.
     Testing Running tests...

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

3-bus case: Test Failed at /Users/melek/.julia/packages/PowerModels/Dhfhc/test/pf.jl:302
  Expression: result["termination_status"] == LOCALLY_SOLVED
   Evaluated: MathOptInterface.NUMERICAL_ERROR == MathOptInterface.LOCALLY_SOLVED

Stacktrace:
 [1] macro expansion
   @ ~/.julia/juliaup/julia-1.11.0+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/PowerModels/Dhfhc/test/pf.jl:302 [inlined]
 [3] macro expansion
   @ ~/.julia/juliaup/julia-1.11.0+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/Test/src/Test.jl:1700 [inlined]
 [4] macro expansion
   @ ~/.julia/packages/PowerModels/Dhfhc/test/pf.jl:300 [inlined]
 [5] macro expansion
   @ ~/.julia/juliaup/julia-1.11.0+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/Test/src/Test.jl:1700 [inlined]
 [6] top-level scope
   @ ~/.julia/packages/PowerModels/Dhfhc/test/pf.jl:299
Test Summary:                                      | Pass  Fail  Total     Time
PowerModels                                        | 4583     1   4584  2m37.2s
  test matpower parser                             |   24           24    11.6s
  test matpower data coercion                      |    6            6     3.1s
  test matpower extentions parser                  |   61           61     0.1s
  test idempotent matpower export                  |   16           16     2.4s
  test matpower export to file                     |    1            1     0.4s
  test pti to matpower                             |    3            3     0.1s
  test matpower export robustness                  |    1            1     0.7s
  test .raw file parser                            |  448          448     0.4s
  test idempotent pti export                       |    8            8     1.9s
  test HVDC Power Flow                             |    1            1     0.3s
  test export all to pti                           |    2            2     0.3s
  test PSS(R)E parser                              |  442          442     2.1s
  export data to other file types                  |   20           20     0.3s
  test output api                                  |   23           23     0.2s
  test branch flow output                          |   47           47     0.2s
  test dual value output                           |  232          232    12.8s
  test solution builder inconsistent status        |    1            1     0.0s
  test solution processors                         |   25           25     1.2s
  test solution feedback                           |   36           36     0.2s
  data modification tests                          |   10           10     0.2s
  test data summary                                |   17           17     1.2s
  test data component table                        |   14           14     0.2s
  test idempotent units transformations            |    9            9     0.1s
  test component status updates                    |  111          111     0.5s
  bus type corrections                             |    1            1     0.0s
  test errors and warnings                         |   21           21     0.3s
  test user ext init                               |    4            4     0.1s
  test impedance to admittance                     |    4            4     0.0s
  test buspair computations                        |    2            2     0.1s
  test theta delta bounds                          |    6            6     0.8s
  test branch flow computations                    |   60           60     0.2s
  test cost model computations                     |   10           10     0.2s
  test power balance computations                  |   60           60     0.8s
  test renumber bus ids                            |    2            2     0.8s
  test resolve switches                            |    3            3     0.2s
  test basic network transformation                |   38           38     0.8s
  test basic network functions                     |  171          171     6.2s
  JuMP model building                              |   10           10     0.3s
  exports for usablity                             |    8            8     0.0s
  relax integrality                                |    5            5     1.7s
  admittance matrix computation                    |   10           10     0.1s
  susceptance matrix computation                   |    8            8     0.5s
  injection factor computation                     |   98           98     0.1s
  test nfa opb                                     |   22           22     1.0s
  test dcp opb                                     |    8            8     0.1s
  test soc wr opb                                  |    8            8     0.3s
  test ac polar pf                                 |   36           36     0.0s
  test ac rect pf                                  |    2            2     0.1s
  test ac tan pf                                   |   11           11     0.2s
  test iv pf                                       |   21           21     1.2s
  test dc pf                                       |   17           17     0.0s
  test matpower dc pf                              |    5            5     0.5s
  test soc pf                                      |    6            6     0.2s
  test soc distflow pf_bf                          |   17     1     18     2.0s
    3-bus case                                     |    9     1     10     1.7s
    5-bus case with hvdc line                      |    2            2     0.2s
    6-bus case                                     |    4            4     0.0s
    24-bus rts case                                |    2            2     0.1s
  test linear distflow pf_bf                       |   21           21     1.0s
  test sdp pf                                      |   18           18     3.1s
  test native dc pf solver                         |   44           44     0.0s
  test native ac pf solver                         |  225          225     0.1s
  test native ac pf solver, in-place               |  217          217     0.0s
  test warm-start ac pf solvers                    |  196          196     0.0s
  test native ac pf solver options                 |   63           63     0.3s
  test ac polar opf                                |   29           29     0.2s
  test ac rect opf                                 |   15           15     0.2s
  test ac tan opf                                  |   17           17     0.2s
  test iv opf                                      |   16           16     1.1s
  test dc opf                                      |   21           21     0.0s
  test matpower dc opf                             |    5            5     0.4s
  test nfa opf                                     |   15           15     0.6s
  test dc+ll opf                                   |   17           17     0.9s
  test lpac-c opf                                  |   23           23     0.3s
  test soc (BIM) opf                               |   21           21     0.1s
  test soc conic form opf                          |   19           19     0.5s
  test soc distflow opf_bf                         |   18           18     0.4s
  test soc conic distflow opf_bf                   |    9            9     1.3s
  test linear distflow opf_bf                      |   17           17     0.4s
  test qc opf                                      |   17           17     0.2s
  test qc opf with trilinear convexhull relaxation |   13           13     2.0s
  test sdp opf                                     |   18           18     2.2s
  test sdp opf with constraint decomposition       |   17           17     4.6s
  test current limit opf                           |   30           30     0.6s
  test mld                                         |  140          140     6.3s
  test unit commitment opf                         |   28           28     9.3s
  test opf with switches                           |   22           22     0.3s
  test oswpf                                       |   31           31     1.2s
  test oswpf node-breaker                          |   12           12     7.3s
  test storage opf                                 |   55           55     1.1s
  test ac v+t polar opf                            |   14           14     0.1s
  test opf with optimization of pst                |   22           22     0.4s
  test opf with optimization of oltc and pst       |   20           20     0.6s
  linear objective                                 |    7            7     0.2s
  quadratic objective                              |    5            5     0.0s
  nlp objective                                    |    5            5     0.1s
  pwl objective                                    |    4            4     0.0s
  dcline objectives                                |   12           12     0.0s
  test ptdf-based dc opf                           |   37           37     0.7s
  test ac ots                                      |   29           29     0.3s
  test dc ots                                      |   50           50     0.2s
  test dc+ll ots                                   |   39           39     0.5s
  test soc ots                                     |   50           50     8.0s
  test qc ots                                      |   60           60     3.2s
  test lpac ots                                    |   60           60     4.7s
  test ac tnep                                     |   11           11     0.8s
  test soc tnep                                    |   11           11     0.2s
  test dc tnep                                     |   11           11     0.6s
  test matpower dc tnep                            |    3            3     0.6s
  test dc-losses tnep                              |    6            6     0.4s
  test lpac tnep                                   |   11           11     1.2s
  test tnep branch flow output                     |   21           21     0.1s
  test multinetwork                                |  310          310     6.4s
  obbt with trilinear convex hull relaxation       |    6            6     1.3s
  obbt with qc relaxation                          |    9            9     0.9s
  opf with flow cuts                               |   94           94     0.2s
  ptdf opf with flow cuts                          |   24           24     0.1s
  dc warm starts                                   |                 0     0.0s
  ac warm starts                                   |                 0     0.0s
  code snippets from docs                          |   11           11     0.0s
ERROR: LoadError: Some tests did not pass: 4583 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /Users/melek/.julia/packages/PowerModels/Dhfhc/test/runtests.jl:32
ERROR: Package PowerModels errored during testing

**Comment by ccoffrin** [comment] 2024-10-19 23:38
These kind of things happen from time to time due to small changes in the numerical methods in the ecosystem. I will look into getting this resolved but it should not impact your usage of PowerModels.

**Comment by ccoffrin** [comment] 2024-10-20 02:33
I can't reproduce, https://github.com/lanl-ansi/PowerModels.jl/actions/runs/11421780261

So I am inclined to close this issue.

**Closed** 2024-11-13 17:53 UTC
