### ISSUE TITLE
Can't parse matpower file

### ISSUE THREAD

**Issue by pedroripper** [lanl-ansi/PowerModels.jl#850] opened 2023-01-12 21:43 UTC
I've tried to parse this [matpower file](https://github.com/MATPOWER/matpower/blob/master/data/case10ba.m) using `PowerModels.parse_file(file_path)` and got the following error:

```
[error | InfrastructureModels]: parsing error, the matlab string "idx_bus" can not be parsed to Int64 data
``` 

My code:
``` julia

using PowerModels

case10_path = joinpath(@__DIR__, "test", "_cases","case10ba.m")
pm_dict = PowerModels.parse_file(case10_path)

```

**Comment by antonhinneck** [comment] 2023-01-19 18:10
I am not a dev but saw your issue while opening my own. 

Based on what you provided, the issue is not your code but your matlab file. While creating your custom file (case10ba.m), you probably deleted a crucial character that the parser expects. At a certain point in your file the parser expects a string that can be parsed into a value of type Int64, but instead finds "idx_bus", which is, obviously, not a number. 

Where you wrote "idx_bus" in your file an integer (like "1") is expected.

I would take a working (pglib) case file as your starting point and be extra careful when making adjustments, keeping the type of values in mind.

Otherwise, just post the content of your matlab file.

**Comment by ccoffrin** [comment] 2023-01-22 00:33
Hi @pedroripper!  The issue with this file you reference is this block of code at the end,

```
%% convert branch impedances from Ohms to p.u.
[PQ, PV, REF, NONE, BUS_I, BUS_TYPE, PD, QD, GS, BS, BUS_AREA, VM, ...
    VA, BASE_KV, ZONE, VMAX, VMIN, LAM_P, LAM_Q, MU_VMAX, MU_VMIN] = idx_bus;
[F_BUS, T_BUS, BR_R, BR_X, BR_B, RATE_A, RATE_B, RATE_C, ...
    TAP, SHIFT, BR_STATUS, PF, QF, PT, QT, MU_SF, MU_ST, ...
    ANGMIN, ANGMAX, MU_ANGMIN, MU_ANGMAX] = idx_brch;
Vbase = mpc.bus(1, BASE_KV) * 1e3;      %% in Volts
Sbase = mpc.baseMVA * 1e6;              %% in VA
mpc.branch(:, [BR_R BR_X]) = mpc.branch(:, [BR_R BR_X]) / (Vbase^2 / Sbase);

%% convert loads from kW to MW
mpc.bus(:, [PD, QD]) = mpc.bus(:, [PD, QD]) / 1e3;
```

When I remove this the data parses, but I don't know if it will work for any analysis because the units would be incorrect.

The core issue here is that PowerModels does not support executing Matlab code, it just reads Matpower data files that do not include any code.  So we consider an example like this one as out of scope.  I am going to close this issue because this data parses correctly when the out of scope code is removed.  Thanks!

**Closed by ccoffrin** 2023-01-22 00:33 UTC

**Comment by pedroripper** [comment] 2023-01-23 17:54
Hi @antonhinneck and @ccoffrin! Thank you for your help!
